# Generated by Django 4.2.16 on 2024-11-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('submissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='submissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='submissao.submissao', verbose_name='Selecione um artigo submetido para avaliação *'),
        ),
    ]
