# Generated by Django 4.2.16 on 2024-11-27 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_evento', '0001_initial'),
        ('instituicao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=150, unique=True, verbose_name='Nome do evento *')),
                ('descricao', models.TextField(blank=True, help_text='Coque aqui uma descrição do evento para ajudar os autores a submeterem seus trabalhos', max_length=500, null=True, verbose_name='Descrição do evento')),
                ('site', models.URLField(blank=True, help_text='Informe o site oficial do evento', max_length=100, null=True, verbose_name='Site do evento')),
                ('data_inicio', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data de início do evento *')),
                ('data_limite_trabalhos', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data limite para envio de trabalhos *')),
                ('data_divulgacao_trabalhos_aprovados', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de divulgação dos trabalhos aprovados *')),
                ('data_limite_reenvio_trabalhos_corrigidos', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de reenvio de trabalhos aprovados e corrigidos *')),
                ('email', models.EmailField(help_text='Campo obrigatório. Email para contato dos membros que estão submetendo trabalhos.', max_length=100, null=True, verbose_name='Email oficial da comissão científica *')),
                ('modelo_artigo', models.CharField(help_text='Informe o modelo, como ABNT, SBC, IEEE', max_length=150, verbose_name='Qual o modelo para artigos? ')),
                ('arquivo_modelo', models.FileField(blank=True, help_text='Utilize arquivo compactado do tipo zip', null=True, upload_to='midias', verbose_name='Carregue arquivo zipado com modelos')),
                ('publicado', models.BooleanField(default=False, help_text='Se marcada a caixa, os resultados das avaliações serão exibidos aos autores de trabalhos', verbose_name='PUBLICAR RESULTADOS APÓS AVALIAÇÕES?')),
                ('data_inscricao', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data limite de inscrição ao evento *')),
                ('carga_horaria', models.DecimalField(decimal_places=0, default=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Carga horária do evento ')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o evento está liberado para chamada de artigos', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador responsável *')),
                ('coordenador_suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador suplente')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituicao', to='instituicao.instituicao', verbose_name='Instituição responsável pelo evento *')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_evento', to='tipo_evento.tipoevento', verbose_name='Tipo do evento *')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-is_active', '-data_inscricao', 'nome'],
            },
        ),
    ]
