# Generated by Django 4.2.16 on 2024-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de início do evento *'),
        ),
    ]
