# Generated by Django 4.2.16 on 2024-11-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_evento_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_limite_trabalhos',
        ),
    ]
