# Generated by Django 5.1.7 on 2025-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_remove_evento_data_limite_trabalhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data do evento *'),
        ),
    ]
