# Generated by Django 5.1.7 on 2025-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='email',
            field=models.EmailField(blank=True, help_text='Campo opcional, caso o evento seja de submissão de trabalhos.', max_length=100, null=True, verbose_name='Email oficial da comissão científica'),
        ),
    ]
