# Generated by Django 5.1.7 on 2025-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_alter_evento_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, help_text='Informe detalhes do local, como sala, prédio, conjunto, etc.', max_length=300, null=True, verbose_name='Local do evento'),
        ),
    ]
