# Generated by Django 5.1.7 on 2025-03-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_alter_evento_lotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='lotacao',
        ),
    ]
