# Generated by Django 4.2.16 on 2024-11-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_alteracao_submissao', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Se for colar texto de outro aplicativo, certifique-se que o título esteja completo', max_length=200, verbose_name='Título *')),
                ('resumo', models.TextField(help_text='Máximo caracteres: 1200. Se for colar texto de outro aplicativo, certifique-se que o resumo esteja completo', max_length=1200, verbose_name='Resumo *')),
                ('abstract', models.TextField(help_text='Máximo caracteres: 1200. Se for colar texto de outro aplicativo, certifique-se que o abstract esteja completo', max_length=1200, verbose_name='Abstract *')),
                ('palavras_chave', models.CharField(help_text='Escreva as palavras-chave separadas por ponto-e-vígura. Exemplo: Redes Neurais; Aprendizado de Máquina; Descoberta de Conhecimento', max_length=100, verbose_name='Palavras-chave *')),
                ('arquivo_sem_autores', models.FileField(help_text='Utilize arquivo .PDF', upload_to='midias', verbose_name='Arquivo PDF de para avaliação (sem autores e identificação)')),
                ('arquivo_final', models.FileField(blank=True, help_text='Utilize arquivo .DOCX e lembre de incluir dados dos autores', null=True, upload_to='midias', verbose_name='Arquivo corrigido para a versão final')),
                ('arquivo_comite_etica', models.FileField(blank=True, help_text='Utilize arquivo compactado .ZIP', null=True, upload_to='midias', verbose_name='Arquivo ZIPADO com documentação necessária de pesquisa em Humanos e Animais')),
                ('status', models.CharField(choices=[('EM EDICAO', 'Em edição'), ('EM AVALIACAO', 'Em avaliação'), ('EM CORRECAO', 'Em correção'), ('APROVADO', 'Aprovado'), ('RETIRADO PELO RESPONSAVEL', 'Retirado pelo responsável'), ('RETIRADO PELO COORDENADOR', 'Retirado pelo coordenador'), ('REPROVADO', 'Reprovado'), ('FINALIZADO', 'Finalizado')], default='EM EDICAO', max_length=25, verbose_name='Status da submissão')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Caso necessite, área para registro de justificativas e/ou apontamentos para o responsável da submissão')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o Submissao está liberado para chamada de artigos', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='evento.evento', verbose_name='Evento para a submissão *')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Autor responsável pela submissão *')),
            ],
            options={
                'verbose_name': 'submissão',
                'verbose_name_plural': 'submissões',
                'ordering': ['-is_active', 'evento', 'responsavel'],
                'unique_together': {('responsavel', 'evento', 'titulo')},
            },
        ),
    ]
